FROM node:8

## Always update
RUN apt-get update

## Node Canvas dependencies
RUN apt-get install -qq libcairo2-dev libjpeg62-turbo-dev libpango1.0-dev libgif-dev build-essential g++

## Chrome/Puppeteer dependencies
RUN apt-get install -yq libgconf-2-4

RUN mkdir -p /opt/node/js \
    && cd /opt/node

WORKDIR /opt/node/js
COPY . /opt/node/js

RUN npm install

# Install latest chrome dev package and fonts to support major charsets (Chinese, Japanese, Arabic, Hebrew, Thai and a few others)
# Note: this installs the necessary libs to make the bundled version of Chromium that Puppeteer
# installs, work.
RUN apt-get update && apt-get install -y wget --no-install-recommends \
    && wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | apt-key add - \
    && sh -c 'echo "deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main" >> /etc/apt/sources.list.d/google.list' \
    && apt-get update \
    && apt-get install -y google-chrome-unstable fonts-ipafont-gothic fonts-wqy-zenhei fonts-thai-tlwg fonts-kacst ttf-freefont \
    --no-install-recommends \
    && rm -rf /var/lib/apt/lists/* \
    && apt-get purge --auto-remove -y curl \
    && rm -rf /src/*.deb

EXPOSE 8888

CMD ["npm", "run", "test"]
